### ISSUE TITLE
Parmed problems with nosetests

### ISSUE THREAD

**Issue by nividic** [MobleyLab/SolvationToolkit#26]
There is an issue with parmed and nosetests. I don't know why on my system nosetests tries to import the python file parmed.py from my binary folder and it is not looking into the python path. I wonder if it depends just on my configuration.

**Comment by davidlmobley** [comment]
Parmed was just rearranged dramatically. Have you reinstalled? Maybe clean out old parmed and try again. I think the setup.py distributed with the new parmed will do this for you.

**Comment by nividic** [comment]
Would you mind running nosetests from your SolvationToolkit dir please?

**Comment by davidlmobley** [comment]
Works for me.

On Tue, Jun 9, 2015 at 1:34 PM, nividic <notifications@github.com> wrote:

> Would you mind running nosetests from your SolvationToolkit dir please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/SolvationToolkit/issues/26#issuecomment-110496360>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by nividic** [comment]
ok good. I would like to see it on Travis CI when mdtraj will be fixed

**Comment by davidlmobley** [comment]
An interim fix is to just add a requirement of the 'pytables' module for
your travis testing. I know Robert McGibbon already fixed mdtraj (earlier
today) but it may be taking some time to make it up onto binstar where
travis gets it from.

On Tue, Jun 9, 2015 at 1:38 PM, nividic <notifications@github.com> wrote:

> ok good. I would like to see it on Travis CI when mdtraj will be fixed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/SolvationToolkit/issues/26#issuecomment-110498002>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
@nividic - I think this is resolved?

**Comment by nividic** [comment]
On my computer is still not working! I ended up changing the name of the parmed.py in myparmed.py. The problem is just between nosetests and parmed.  However, the test did not fail on travis and I'm assuming that could be my computer setting.

**Comment by davidlmobley** [comment]
Ah, wait, I think maybe I know the issue and ran into it myself: The old
parmed included a `parmed.py` script which was a command-line tool, and the
name of the module was `chemistry`. The new parmed module (v2.0 beta) was
renamed `parmed` (logically), and the `parmed.py` command-line script is
renamed (I think to just `parmed` so that `import parmed` doesn't try to
import it). HOWEVER, if you're installing the new version on top of an old
installation, sometimes you'll end up with an old copy of the `parmed.py`
script still hanging around which causes problems because nosetests and
IPython will try and import it.

The solution, since the `parmed.py` script is unneeded and old, is to just
delete it (which is effectively what you've done by renaming it).

So - I think this is resolved,then?

On Thu, Jun 25, 2015 at 9:20 AM, nividic <notifications@github.com> wrote:

> On my computer is still not working! I ended up changing the name of the
> parmed.py in myparmed.py. The problem is just between nosetests and parmed.
> However, the test did not fail on travis and I'm assuming that could be my
> computer setting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/SolvationToolkit/issues/26#issuecomment-115308278>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by nividic** [comment]
That is great! I did not know that. Thanks. Then the issue should be closed
